### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position 362

### ISSUE THREAD

**Issue by pkadanec** [timcharper/homebridge-vivint#11]

**Comment by pkadanec** [comment]
SyntaxError: Unexpected token } in JSON at position 362
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:212:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Any ideas?
