### ISSUE TITLE
Error connecting to panel

### ISSUE THREAD

**Issue by MarkHerb** [timcharper/homebridge-vivint#28]
Just set up Home bridge. MacPro2010, Mojave, 
Some oddities. Password has spaces in it.
No longer paying Vivint.
I get this error:
[5/8/2020, 9:53:05 AM] Homebridge is running on port 51468.
[5/8/2020, 9:53:05 AM] [Vivint] Error while bootstrapping accessories
[5/8/2020, 9:53:05 AM] [Vivint] TypeError: Cannot read property 'panid' of undefined
    at /usr/local/lib/node_modules/homebridge-vivint-latest/lib/vivint_api.js:113:45
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by daymondm** [comment]
Hi @MarkHerb, I do believe you need a paid account for this to work. The plugin essentially logs in to Vivintsky.com and reads api notifications from there. My account is for app access only, unmonitored which is $19.99 per month.

**Comment by MarkHerb** [comment]
Thanks very much for the info. That is too bad.
Vivint did not offer that option. Not sure I would have taken it if they did.
I will just rebuild my own system without the vivint stuff and without monthly charges.
