### ISSUE TITLE
Vivint Authentication Error Oct 2024

### ISSUE THREAD

**Issue by ffemt-asher** [timcharper/homebridge-vivint#47]
I have tried a few different things to get this fixed. I refreshed the token, reinstalled the bridge and made sure all updates have been installed. This is the error I am seeing in the homebride log. 

[11/1/2024, 5:25:26 PM] [@balansse/homebridge-vivint] Error occurred during login, retrying in 60 seconds... StatusCodeError: 401 - "<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body>\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request/request.js:185:22)
    at Request.emit (node:events:518:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:518:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/@balansse/homebridge-vivint/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:632:28)
    at IncomingMessage.emit (node:events:530:35) {
  statusCode: 401,
  error: '<html>\r\n' +
    '<head><title>401 Authorization Required</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>401 Authorization Required</h1></center>\r\n' +
    '<hr><center>nginx</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n',

**Comment by ffemt-asher** [comment]
@timcharper Any ideas on what can be causing this?

**Comment by ffemt-asher** [comment]
Sorry I think this error was for a different repo.
